### PR TITLE
Remove options.body for GET requests

### PR DESCRIPTION
**Pull request by benpbolton**
From Harvest:

>  After August 15 2021, Harvest's new infrastructure will return an error on GET requests with content in the BODY payload. Requests matching this pattern will receive an error 400.

> Please ... adjust all GET requests to send an empty BODY payload following the HTTP 1.1 spec. We strongly recommend doing this well before August 15, 2021 in order to avoid any issues.

### CODE REVIEW

**Comment by benpbolton** [comment]
I'm... fairly certain this project is deprecated (request, a major dependency, is deprecated itself). But if someone stumbles across this and wishes to implement it, it's important to note that you'll have to `JSON.parse` the responses as we're no longer setting options.json to true (because, in this version of request, it sends an empty json payload for `GET` requests? )

**Comment by benpbolton** [comment]
Closing this out in favor of an updated fork.

**Comment by Yaaqoub** [comment]
@benpbolton You can make a pull request I will verify everything and accept it, also there is new changes in Harvest API I will make sure to add them sooner.

**Comment by benpbolton** [comment]
🎉  I was under the mistaken belief that this project was abandoned. I opened https://github.com/Yaaqoub/node-harvest-v2/pull/79 for your review/consideration.

**Pull request closed without merging**
